% This LilyPond file was generated by Rosegarden 20.12
\include "nederlands.ly"
\version "2.6.0"
\header {
    arranger = "find me"
    composer = "find me"
    copyright =  \markup { "Copyright "\char ##x00A9" xxxx El Usuario" }
    dedication = "find me"
    instrument = "find me"
    meter = "find me"
    opus = "find me"
    piece = "find me"
    poet = "find me"
    subsubtitle = "find me"
    subtitle = "todavía sin subtítulo"
    tagline = "find me"
    title = "Todavía sin título"
}
#(set-global-staff-size 32)
#(set-default-paper-size "a4")
global = { 
    \time 4/4
    \skip 1*117 
}
globalTempo = {
    \override Score.MetronomeMark #'transparent = ##t
    \tempo 4 = 113  
}
\score {
    << % common
        % Force offset of colliding notes in chords:
        \override Score.NoteColumn #'force-hshift = #1.0
        % Allow fingerings inside the staff (configured from export options):
        \override Score.Fingering #'staff-padding = #'()

        \new TabStaff = "track 1, Bajo (GM)" << 
            \set Staff.instrument = \markup { \center-column { "Bajo (GM) " } }
            \set Staff.midiInstrument = ""
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 1" {
                % Segment: Bajo (GM)
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1
                \once \override Staff.TimeSignature #'style = #'() 
                \time 4/4
                
                \clef "treble"
                \key a \minor
                R1*117  |
                \bar "|."
            } % Voice
        >> % Staff ends

        \new TabStaff = "track 2, Bajo (GM)" << 
            \set Staff.instrument = \markup { \center-column { "Bajo (GM) " } }
            \set Staff.midiInstrument = "Fingered Bass"
            \set Score.skipBars = ##t
            \set Staff.printKeyCancellation = ##f
            \new Voice \global
            \new Voice \globalTempo

            \context Voice = "voice 2" {
                % Segment: Bajo (GM)
                \override Voice.TextScript #'padding = #2.0
                \override MultiMeasureRest #'expand-limit = 1

                \skip 1*2 \skip 2 
                \clef "bass_15"
                \key a \minor
                g 16 a g g a g g a g g a g 32 
                % aviso: compás demasiado largo truncado aquí |
                g 16 a g g a g g a g g a g g a g g a g g a g g a g 32 
                % aviso: compás demasiado largo truncado aquí |
%% 5
                g 8 r r4 r2  |
                R1  |
                a,, 4 r a,, 8 c, e, d, 
                % aviso: compás demasiado largo truncado aquí |
                \skip 4 r4 r8 c, a,, g,,  |
                a,, 4 r a,, 8 c, e, d, 
                % aviso: compás demasiado largo truncado aquí |
%% 10
                \skip 4 r8 d d, d, d, g,,  |
                a,, 4 r a,, 8 c, e, d, 
                % aviso: compás demasiado largo truncado aquí |
                \skip 4 r4 r8 c, a,, g,,  |
                a,, 4 r a,, 8 c, e, d,  |
                R1  |
%% 15
                a,, 4 r8 a,, c, r d,, d,,  |
                r2 g,, 8 g,, gis,, gis,,  |
                a,, 4 r8 a,, c, r d,, d,,  |
                r2 e,, 8 g,, a,, b,,  |
                c, 4 r8 c, 4. r8 c,  |
%% 20
                d, 4 r8 d, 4. a,, 8 bes,,  |
                b,, 4 r8 b,, 4. r8 e,, 
                % aviso: compás demasiado largo truncado aquí |
                \skip 8 e,, 8 e,, e, e,, e,, e,, 4  |
                a,, 4 r8 a,, c, r d,, d,,  |
                r2 g,, 8 g,, gis,, gis,,  |
%% 25
                a,, 4 r8 a,, c, r d,, d,,  |
                r4 r8 d, d, d, a,, b,,  |
                c, 4 r8 c, 4. c 8 c,  |
                d, 4 r8 d,, d,, 4 d, 8 a,,  |
                b,, 4 r8 b,, 4. r8 e,,  |
%% 30
                e,, 4 -\tenuto r8 e,, e,, e,, e,, e,,  |
                e,, 4 r r2  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r4 r8 d, e,, g,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
%% 35
                r8 d,, r4 c, 8 d, e,, g,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r4 r8 d, e,, g,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r d, r d, e,, g,,  |
%% 40
                a,, 4 r8 a,, 4 g, 8 a, g,,  |
                f,, 4 r8 f,, 4 f, 8 f,, f,,  |
                c, 4 r8 c, 4. c, 8 a,,  |
                d, 4 r8 d,, r d, d, e, 
                % aviso: compás demasiado largo truncado aquí |
                \skip 8 e,, 8 e,, e,, e, e,, e,, e,,  |
%% 45
                e,, 8 r r4 r2  |
                a,, 4 r8 a,, c, r d,, d,,  |
                r4 r8 d, g,, g,, gis,, gis,,  |
                a,, 4 r8 a,, c, r d,, d,,  |
                r8 a,, a,, a,, a,, c, d, g,,  |
%% 50
                c, 4 r8 c, 4. g, 8 c,  |
                d, 4 r8 d,, 4. d, 8 a,,  |
                b,, 4 r8 b,, 4. r8 e,,  |
                e,, 8 d,, e, e,, e,, e, e,, e,,  |
                a,, 4 r8 a,, c, r d,, d,,  |
%% 55
                r8 d, r d,, 16 d,, g,, 8 d,, 16 d,, gis,, 8 d,, 16 d,,  |
                a,, 4 r8 g,, c, r r d,  |
                r8 d r d, d,, d, d,, g,,  |
                c, 4 r8 c, 4. r8 c,  |
                d, 4 r8 d,, r4 d, 8 a,,  |
%% 60
                b,, 4 r8 b,, r a,, b,, e,, 
                % aviso: compás demasiado largo truncado aquí |
                \skip 8 e,, 8 e,, e, e,, e,, e, r  |
                e,, 4 r r2  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, d,, d,, d,, d,, e,, g,,  |
%% 65
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r4 r8 d, e,, g,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, d,, d,, d,, d,, e,, g,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
%% 70
                r8 d,, r d, r d,, d, g,,  |
                a,, 4 r8 a,, 4 g, 8 a, g,,  |
                f,, 4 r8 f,, 4 f, 8 f,, f,,  |
                c, 4 r8 c,, c,, c, c,, c,,  |
                d,, 4 r8 d, r d,, d, e, 
                % aviso: compás demasiado largo truncado aquí |
%% 75
                \skip 8 e,, 8 e,, e,, e, e,, e,, e,  |
                e,, 8 r r4 r2  |
                d,, 4 r8 fis,, r a,, a,, d, 16 e,  |
                d, 4 r8 c, r4 b,, 8 g,,  |
                a,, 4 r8 c, r4 e, 8 g,  |
%% 80
                a, 4 r8 a,, r a,, c, e,  |
                d, 4 r8 fis,, r a,, a,, d, 16 e,  |
                d, 4 r8 d,, c, d,, g,, gis,,  |
                a,, 4 r8 c, r4 e, 8 g,  |
                a, 8 c a, 4 e, 8 c, a,, g,,  |
%% 85
                d,, 4 r8 fis,, r a,, a,, d, 16 e,  |
                d, 4 r8 d,, r d, d,, e,, 
                % aviso: compás demasiado largo truncado aquí |
                \skip 8 e,, 8 e, d,, e,, e, e,, e,,  |
                e, 4 r r2  |
                a,, 4 r8 a,, c, 4 r8 d,  |
%% 90
                r8 d,, r d, r d,, d, g,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r d, r d,, g,, gis,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r c, d, d,, g,, gis,,  |
%% 95
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r a,, 16 a,, c, d, 8. d,, 4  |
                a,, 4 r8 a,, 4 g, 8 a, g,,  |
                f,, 4 r8 f,, 4 f,, 8 f, f,,  |
                c, 4 r8 c,, 4. c, 8 c,  |
%% 100
                d, 4 r8 d, r d, d, e, 
                % aviso: compás demasiado largo truncado aquí |
                \skip 8 e,, 8 e,, e,, d, e, e,, e,,  |
                e, 8 r r4 r2  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r d, r c, d, g,,  |
%% 105
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 a, f < fis, d > 4. d, 4  |
                a,, 4 r8 a,, c, 4 r8 d,  |
                r8 d,, r d, d,, d,, g,, gis,,  |
                a,, 4 r8 a,, c, 4 r8 d,  |
%% 110
                r8 d,, r c, d, d,, d, g,,  |
                a,, 4 r8 a,, 4 a, 8 a,, g,,  |
                f,, 4 r8 f,, 4 f, 8 f,, f,,  |
                c, 4 r8 c,, r c,, c, c,  |
                d, 4 r8 d, r d, c, e, 
                % aviso: compás demasiado largo truncado aquí |
%% 115
                \skip 8 e,, 8 e,, e,, e, e,, e,, e,,  |
                e, 8 r r4 g,, 16 a,, c, a,, e, c, d, 8 -\tenuto 
                % aviso: compás demasiado largo truncado aquí |
                \skip 4 \skip 8 r8 r a,, 16 g,, e,, c, a,, 8  |
                \bar "|."
            } % Voice
        >> % Staff (final) ends

    >> % notes

    \layout {
        indent = 3.0\cm
        short-indent = 1.5\cm
        \context { \Staff \RemoveEmptyStaves }
        \context { \GrandStaff \accepts "Lyrics" }
    }
%     uncomment to enable generating midi file from the lilypond source
%         \midi {
%             \tempo 4 = 113
%         } 
} % score
